#ifndef ADDITIONALCOLUMNTYPE_H
#define ADDITIONALCOLUMNTYPE_H

enum class AdditionalColumnType {

    NONE_ADDITIONAL_COLUMN = 0,
    ANALYZE_ADDITIONAL_COLUMN_TYPE = 1,
    TEST_ADDITIONAL_COLUMN_TYPE = 2
};

#endif // ADDITIONALCOLUMNTYPE_H
