#ifndef PARSERTAGNAMES_H
#define PARSERTAGNAMES_H

#define NEEDED_TAG "error"
#define FILE_LOCATION_ATTRIBUTE "file"
#define LINE_ATTRIBUTE "line"
#define ERROR_TYPE_ATTRIBUTE "severity"
#define DESCRIPTION_ATTRIBUTE "msg"

#endif // PARSERTAGNAMES_H
