#ifndef TYPESTATICANALYZERTEXT_H
#define TYPESTATICANALYZERTEXT_H

#define ERROR_TYPE_ANALYZE_TEXT "error"

#define STYLE_TYPE_ANALYZE_DESCRIPTION "Стиль"
#define ERROR_TYPE_ANALYZE_DESCRIPTION "Ошибка"
#define WARNING_TYPE_ANALYZE_DESCRIPTION "Предупреждение"

#endif // TYPESTATICANALYZERTEXT_H
