#ifndef DEFINITIONSFORREQAUTH_H
#define DEFINITIONSFORREQAUTH_H

#define TABLE_NAME_FOR_TEACHER_AUTH "teacher_auth"
#define FIRST_FILED_TITLE_FOR_TEACHER_ATUH "login"
#define SECOND_FIELD_TITLE_FOR_TEACHER_AUTH "password"
#define ID_FIELD_TITLE_FOR_TEACHER_AUTH "id_teacher"

#endif // DEFINITIONSFORREQAUTH_H
